

/*
 * Copyright 2021 Michael Kraley
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {Picker, Item} from '@adobe/react-spectrum'
import {addLogRecord, ControlValue} from "./logging";

const fileHTML: {[key: string]: string} = {
Learning_from_History: `<!DOCTYPE html>
<html lang="en-US" xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>Learning_from_History-tagged.pdf</title>
<meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
<meta content="width=device-width, initial-scale=1" name="viewport"/>
<meta content="pdfStructure" name="generator"/>
</head>
<body>
<div class="ADBE_E_Document" id="ADBE_Obj_181">
<section class="ADBE_E_Sect" id="ADBE_Obj_228">
<h1 class="ADBE_E_Title" data-page="1" id="ADBE_Obj_223" lang="en">Learning from History </h1>
<p class="ADBE_E_P" data-page="1" id="ADBE_Obj_224" lang="en">Andy Nash </p>
<p class="ADBE_E_P ADBE_CM_CM2" data-page="1" id="ADBE_Obj_225" lang="en">Many people are worried that the information they provide to the Census Bureau in 2020 will be shared with other government agencies. Here’s how that happened in the past and what’s differ<span class="ADBE_E_HyphenSpan" data-page="1" id="ADBE_Obj_226">­</span>ent now. </p>
</section>
<section class="ADBE_E_Sect" id="ADBE_Obj_209">
<h1 class="ADBE_E_H1" data-page="1" id="ADBE_Obj_210" lang="en">How Census Data Was Misused in the Past </h1>
<p class="ADBE_E_P ADBE_CM_CM2" data-page="1" id="ADBE_Obj_211" lang="en">In 1941, Japan attacked Pearl Harbor in Hawaii. The attack raised Americans’ fear of war and intensified racial prejudices against Japanese Americans. In the days after the bombing, the U.S. government arrested more than 1,200 Japanese community leaders and froze all bank accounts in U.S. branches of Japanese banks. The government also imposed nighttime curfews for all Japanese Americans. </p>
<p class="ADBE_E_P ADBE_CM_CM2" id="ADBE_Obj_212" lang="en">
<span class="ADBE_E_ParagraphSpan" data-page="1" id="ADBE_Obj_220">Within months, President Roosevelt signed an order that allowed the military to round up 120,000 Americans of Japanese descent (who were mostly native-born U.S. citizens). The government gave Japanese-Americans on the West Coast only days </span><span class="ADBE_E_ParagraphSpan" data-page="1" id="ADBE_Obj_221">to decide what to do with their houses, farms, businesses, and possessions. According to the Manzanar National Historic Site webpage, “Most families sold their property and belongings for much less than they were worth. Some rented their properties to neighbors. Others left possessions with friends or religious groups. Some abandoned their property. They did not know where they were going or for how long. Each family was assigned an identification number and loaded into cars, buses, trucks, and trains, taking only what they could carry.” The military transported Japanese Americans to temporary centers at racetracks and fairgrounds, and then took them to internment camps until the end of the war. </span></p>
<p class="ADBE_E_P ADBE_CM_CM2" id="ADBE_Obj_213" lang="en">
<span class="ADBE_E_ParagraphSpan" data-page="1" id="ADBE_Obj_214">To make this round-up go more quickly, Con<span class="ADBE_E_HyphenSpan" data-page="1" id="ADBE_Obj_219">­</span>gress passed a law that allowed the military to see confidential census information about individuals. Although the Census Bureau denied it for decades, researchers Margo Anderson and William Seltzer discovered that census officials had released block-by-block information about where Japanese-</span><span class="ADBE_E_ParagraphSpan" data-page="2" id="ADBE_Obj_184">Americans were living in California, Arizona, Wyoming, Colorado, Utah, Idaho, and Arkansas. </span></p>
<p class="ADBE_E_P ADBE_CM_CM2" data-page="2" id="ADBE_Obj_185" lang="en">World War II is not the only time that the Census Bureau has shared information about individuals or communities. During World War I, the Draft Board got information from the Census Bureau to check the age of citizens they believed were lying about their age to avoid the draft. And after the 9/11 terrorist attacks, the Census Bureau gave the U.S. Deptartment of Homeland Security information about neighborhoods that were home to large numbers of Arab Americans, sorted by their country of origin. In this case, the informa<span class="ADBE_E_HyphenSpan" data-page="2" id="ADBE_Obj_186">­</span>tion was publicly available, but not useful until the Census Bureau organized and shared it. The government claimed that the requests were made to help identify which airports required signs and pamphlets in Arabic to explain U.S. laws and regu<span class="ADBE_E_HyphenSpan" data-page="2" id="ADBE_Obj_187">­</span>lations to travelers. </p>
<p class="ADBE_E_P ADBE_CM_CM2" data-page="2" id="ADBE_Obj_188" lang="en">In response to concerns about this misuse of data, the Census Bureau implemented additional procedures to protect information requested by federal, state, or local law enforcement agencies or that involves a “sensitive population.” </p>
</section>
<section class="ADBE_E_Sect" id="ADBE_Obj_205">
<h1 class="ADBE_E_H1" data-page="2" id="ADBE_Obj_189" lang="en">Strategies for Making Data Safe in 2020 </h1>
<p class="ADBE_E_P ADBE_CM_CM2" data-page="2" id="ADBE_Obj_190" lang="en">There are three important ways that our data is being protected this year. First, current law (see p. 7 for more information about Title 13) ensures that individual information cannot be shared with any other agencies, including Immigration and Cus<span class="ADBE_E_HyphenSpan" data-page="2" id="ADBE_Obj_191">­</span>toms Enforcement (ICE), the FBI, the CIA or any other government agency. And no private compa<span class="ADBE_E_HyphenSpan" data-page="2" id="ADBE_Obj_192">­</span>ny, landlord, or employer can get any household’s census information, even with a court order. </p>
<p class="ADBE_E_P ADBE_CM_CM2" data-page="2" id="ADBE_Obj_193" lang="en">Second, the Census Bureau is using some strategies to protect against hackers. For example, the Census Bureau will scramble the data by swap<span class="ADBE_E_HyphenSpan" data-page="2" id="ADBE_Obj_194">­</span>ping the information from two similar households in different neighborhoods. Mixing up individual information in this way ensures the aggregate data is accurate, while individual data is not traceable. </p>
<p class="ADBE_E_P ADBE_CM_CM2" id="ADBE_Obj_206" lang="en">
<span class="ADBE_E_ParagraphSpan" data-page="2" id="ADBE_Obj_195">And finally, civil liberties groups such as the ACLU and Asian-Americans Advancing Justice are preparing to respond quickly in the courts if </span><span class="ADBE_E_ParagraphSpan" data-page="2" id="ADBE_Obj_196">any data are used improperly. </span></p>
<p class="ADBE_E_P ADBE_CM_CM2" data-page="2" id="ADBE_Obj_197" lang="en">The fact is, there is never a way to be 100% sure that our civil rights and personal information are safe, especially during times of war. And this is not unique to the census. We need to constantly work to safeguard our rights and our personal data. We also have a responsibility to contribute to a full, accurate count of our population so that our communities get our fair share of the tax dol<span class="ADBE_E_HyphenSpan" data-page="2" id="ADBE_Obj_198">­</span>lars we have paid. We can’t let anyone steal those resources by frightening us away from the census. </p>
</section>
</div>
</body>
</html>
`,
Rapunzel: `<html lang="EN-US" xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>Rapunzel-tagged.pdf</title>
<meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
<meta content="width=device-width, initial-scale=1" name="viewport"/>
<meta content="pdfStructure" name="generator"/>
</head>
<body>
<div class="ADBE_E_Document" id="ADBE_Obj_76">
<section class="ADBE_E_Sect" id="ADBE_Obj_81">
<h1 class="ADBE_E_Title" data-page="1" id="ADBE_Obj_84" lang="en">RAPUNZEL </h1>
<p class="ADBE_E_P ADBE_CM_ADBE_CM_FULL_JUSTIFICATION ADBE_CM_CM1 ADBE_CM_CM6" data-page="1" id="ADBE_Obj_85" lang="en">There were once a man and a woman who had long in vain wished for a child. At length the woman hoped that God was about to grant her desire. These people had a little window at the back of their house from which a splendid garden could be seen, which was full of the most beautiful flowers and herbs. It was, however, surrounded by a high wall, and no one dared to go into it because it belonged to an enchantress, who had great power and was dreaded by all the world. One day the woman was standing by this window and looking down into the garden, when she saw a bed which was planted with the most beautiful rampion (rapunzel), and it looked so fresh and green that she longed for it, she quite pined away, and began to look pale and miserable. Then her husband was alarmed, and asked: ‘What ails you, dear wife?’ ‘Ah,’ she replied, ‘if I can’t eat some of the rampion, which is in the garden behind our house, I shall die.’ The man, who loved her, thought: ‘Sooner than let your wife die, bring her some of the rampion yourself, let it cost what it will.’ At twilight, he clambered down over the wall into the garden of the enchantress, hastily clutched a handful of rampion, and took it to his wife. She at once made herself a salad of it, and ate it greedily. It tasted so good to her—so very good, that the next day she longed for it three times as much as before. If he was to have any rest, her husband must once more descend into the garden. In the gloom of evening therefore, he let himself down again; but when he had clambered down the wall he was terribly afraid, for he saw the enchantress standing before him. ‘How can you dare,’ said she with angry look, ‘descend into my garden and steal my rampion like a thief? You shall suffer for it!’ ‘Ah,’ answered he, ‘let mercy take the place of justice, I only made up my mind to do it out of necessity. My wife saw your rampion from the window, and felt such a longing for it that she would have died if she had not got some to eat.’ Then the enchantress allowed her anger to be softened, and said to him: ‘If the case be as you say, I will allow you to take away with you as much rampion as you will, only I make one condition, you must give me the child which your wife will bring into the world; it shall be well treated, and I will care for it like a mother.’ The man in his terror consented to everything, and when the woman was brought to bed, the enchantress appeared at once, gave the child the name of Rapunzel, and took it away with her. </p>
<p class="ADBE_E_P ADBE_CM_ADBE_CM_FULL_JUSTIFICATION ADBE_CM_CM1 ADBE_CM_CM6" data-page="1" id="ADBE_Obj_86" lang="en">Rapunzel grew into the most beautiful child under the sun. When she was twelve years old, the enchantress shut her into a tower, which lay in a forest, and had neither stairs nor door, but quite at the top was a little window. When the enchantress wanted to go in, she placed herself beneath it and cried: </p>
<p class="ADBE_E_P" data-page="1" id="ADBE_Obj_87" lang="en">‘Rapunzel, Rapunzel, </p>
<p class="ADBE_E_P ADBE_CM_CM6" data-page="1" id="ADBE_Obj_88" lang="en">Let down your hair to me.’ </p>
<p class="ADBE_E_P ADBE_CM_CM3 ADBE_CM_CM6" id="ADBE_Obj_89" lang="en">
<span class="ADBE_E_ParagraphSpan" data-page="1" id="ADBE_Obj_112">Rapunzel had magnificent long hair, fine as spun gold, and when she heard the voice of the enchantress she unfastened her braided tresses, wound them round one of the </span><span class="ADBE_E_ParagraphSpan" data-page="2" id="ADBE_Obj_113">hooks of the window above, and then the hair fell twenty ells down, and the enchantress climbed up by it. </span></p>
<p class="ADBE_E_P ADBE_CM_ADBE_CM_FULL_JUSTIFICATION ADBE_CM_CM1 ADBE_CM_CM6" data-page="2" id="ADBE_Obj_90" lang="en">After a year or two, it came to pass that the king’s son rode through the forest and passed by the tower. Then he heard a song, which was so charming that he stood still and listened. This was Rapunzel, who in her solitude passed her time in letting her sweet voice resound. The king’s son wanted to climb up to her, and looked for the door of the tower, but none was to be found. He rode home, but the singing had so deeply touched his heart, that every day he went out into the forest and listened to it. Once when he was thus standing behind a tree, he saw that an enchantress came there, and he heard how she cried: </p>
<p class="ADBE_E_P" data-page="2" id="ADBE_Obj_91" lang="en">‘Rapunzel, Rapunzel, </p>
<p class="ADBE_E_P ADBE_CM_CM6" data-page="2" id="ADBE_Obj_92" lang="en">Let down your hair to me.’ </p>
<p class="ADBE_E_P ADBE_CM_ADBE_CM_FULL_JUSTIFICATION ADBE_CM_CM1 ADBE_CM_CM6" data-page="2" id="ADBE_Obj_93" lang="en">Then Rapunzel let down the braids of her hair, and the enchantress climbed up to her. ‘If that is the ladder by which one mounts, I too will try my fortune,’ said he, and the next day when it began to grow dark, he went to the tower and cried: </p>
<p class="ADBE_E_P" data-page="2" id="ADBE_Obj_94" lang="en">‘Rapunzel, Rapunzel, </p>
<p class="ADBE_E_P ADBE_CM_CM6" id="ADBE_Obj_95" lang="en">
<span class="ADBE_E_Sub" data-page="2" id="ADBE_Obj_105">Let down your hair to me.’ </span><span class="ADBE_E_Sub" data-page="2" id="ADBE_Obj_106">Immediately the hair fell down and the king’s son climbed up. </span></p>
<p class="ADBE_E_P ADBE_CM_ADBE_CM_FULL_JUSTIFICATION ADBE_CM_CM1 ADBE_CM_CM6" data-page="2" id="ADBE_Obj_96" lang="en">At first Rapunzel was terribly frightened when a man, such as her eyes had never yet beheld, came to her; but the king’s son began to talk to her quite like a friend, and told her that his heart had been so stirred that it had let him have no rest, and he had been forced to see her. Then Rapunzel lost her fear, and when he asked her if she would take him for her husband, and she saw that he was young and handsome, she thought: ‘He will love me more than old Dame Gothel does’; and she said yes, and laid her hand in his. She said: ‘I will willingly go away with you, but I do not know how to get down. Bring with you a skein of silk every time that you come, and I will weave a ladder with it, and when that is ready I will descend, and you will take me on your horse.’ They agreed that until that time he should come to her every evening, for the old woman came by day. The enchantress remarked nothing of this, until once Rapunzel said to her: ‘Tell me, Dame Gothel, how it happens that you are so much heavier for me to draw up than the young king’s son—he is with me in a moment.’ ‘Ah! you wicked child,’ cried the enchantress. ‘What do I hear you say! I thought I had separated you from all the world, and yet you have deceived me!’ In her anger she clutched Rapunzel’s beautiful tresses, wrapped them twice round her left hand, seized a pair of scissors with the right, and snip, snap, they were cut off, and the lovely braids lay on the ground. And she was so pitiless that she took poor Rapunzel into a desert where she had to live in great grief and misery. </p>
<p class="ADBE_E_P ADBE_CM_ADBE_CM_FULL_JUSTIFICATION ADBE_CM_CM1 ADBE_CM_CM6" data-page="2" id="ADBE_Obj_97" lang="en">On the same day that she cast out Rapunzel, however, the enchantress fastened the braids of hair, which she had cut off, to the hook of the window, and when the king’s son came and cried: </p>
<p class="ADBE_E_P" data-page="2" id="ADBE_Obj_98" lang="en">‘Rapunzel, Rapunzel, </p>
<p class="ADBE_E_P" data-page="2" id="ADBE_Obj_99" lang="en">Let down your hair to me.’ </p>
<p class="ADBE_E_P ADBE_CM_ADBE_CM_FULL_JUSTIFICATION ADBE_CM_CM1" data-page="3" id="ADBE_Obj_80" lang="en">she let the hair down. The king’s son ascended, but instead of finding his dearest Rapunzel, he found the enchantress, who gazed at him with wicked and venomous looks. ‘Aha!’ she cried mockingly, ‘you would fetch your dearest, but the beautiful bird sits no longer singing in the nest; the cat has got it, and will scratch out your eyes as well. Rapunzel is lost to you; you will never see her again.’ The king’s son was beside himself with pain, and in his despair he leapt down from the tower. He escaped with his life, but the thorns into which he fell pierced his eyes. Then he wandered quite blind about the forest, ate nothing but roots and berries, and did naught but lament and weep over the loss of his dearest wife. Thus he roamed about in misery for some years, and at length came to the desert where Rapunzel, with the twins to which she had given birth, a boy and a girl, lived in wretchedness. He heard a voice, and it seemed so familiar to him that he went towards it, and when he approached, Rapunzel knew him and fell on his neck and wept. Two of her tears wetted his eyes and they grew clear again, and he could see with them as before. He led her to his kingdom where he was joyfully received, and they lived for a long time afterwards, happy and contented. </p>
</section>
</div>
</body>
</html>`,

Rumpelstiltskin: `
<html lang="EN-US" xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>Rumpelstiltskin-tagged.pdf</title>
<meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
<meta content="width=device-width, initial-scale=1" name="viewport"/>
<meta content="pdfStructure" name="generator"/>
</head>
<body>
<div class="ADBE_E_Document" id="ADBE_Obj_86">
<section class="ADBE_E_Sect" id="ADBE_Obj_92">
<h1 class="ADBE_E_Title" data-page="1" id="ADBE_Obj_95" lang="en">RUMPELSTILTSKIN </h1>
<p class="ADBE_E_P ADBE_CM_ADBE_CM_FULL_JUSTIFICATION ADBE_CM_CM1 ADBE_CM_CM8" data-page="1" id="ADBE_Obj_96" lang="en">By the side of a wood, in a country a long way off, ran a fine stream of water; and upon the stream there stood a mill. The miller’s house was close by, and the miller, you must know, had a very beautiful daughter. She was, moreover, very shrewd and clever; and the miller was so proud of her, that he one day told the king of the land, who used to come and hunt in the wood, that his daughter could spin gold out of straw. Now this king was very fond of money; and when he heard the miller’s boast his greediness was raised, and he sent for the girl to be brought before him. Then he led her to a chamber in his palace where there was a great heap of straw, and gave her a spinning-wheel, and said, ‘All this must be spun into gold before morning, as you love your life.’ It was in vain that the poor maiden said that it was only a silly boast of her father, for that she could do no such thing as spin straw into gold: the chamber door was locked, and she was left alone. </p>
<p class="ADBE_E_P ADBE_CM_ADBE_CM_FULL_JUSTIFICATION ADBE_CM_CM1 ADBE_CM_CM8" data-page="1" id="ADBE_Obj_97" lang="en">She sat down in one corner of the room, and began to bewail her hard fate; when on a sudden the door opened, and a droll-looking little man hobbled in, and said, ‘Good morrow to you, my good lass; what are you weeping for?’ ‘Alas!’ said she, ‘I must spin this straw into gold, and I know not how.’ ‘What will you give me,’ said the hobgoblin, ‘to do it for you?’ ‘My necklace,’ replied the maiden. He took her at her word, and sat himself down to the wheel, and whistled and sang: </p>
<p class="ADBE_E_P" data-page="1" id="ADBE_Obj_98" lang="en">‘Round about, round about, </p>
<p class="ADBE_E_P" data-page="1" id="ADBE_Obj_99" lang="en">Lo and behold! </p>
<p class="ADBE_E_P ADBE_CM_CM3 ADBE_CM_CM8" id="ADBE_Obj_100" lang="en">
<span class="ADBE_E_Sub" data-page="1" id="ADBE_Obj_140">Reel away, reel away, </span><span class="ADBE_E_Sub" data-page="1" id="ADBE_Obj_141">Straw into gold!’ </span></p>
<p class="ADBE_E_P ADBE_CM_CM4 ADBE_CM_CM8" data-page="1" id="ADBE_Obj_101" lang="en">And round about the wheel went merrily; the work was quickly done, and the straw was all spun into gold. </p>
<p class="ADBE_E_P ADBE_CM_ADBE_CM_FULL_JUSTIFICATION ADBE_CM_CM1 ADBE_CM_CM8" data-page="1" id="ADBE_Obj_102" lang="en">When the king came and saw this, he was greatly astonished and pleased; but his heart grew still more greedy of gain, and he shut up the poor miller’s daughter again with a fresh task. Then she knew not what to do, and sat down once more to weep; but the dwarf soon opened the door, and said, ‘What will you give me to do your task?’ ‘The ring on my finger,’ said she. So her little friend took the ring, and began to work at the wheel again, and whistled and sang: </p>
<p class="ADBE_E_P" data-page="1" id="ADBE_Obj_103" lang="en">‘Round about, round about, </p>
<p class="ADBE_E_P" data-page="1" id="ADBE_Obj_104" lang="en">Lo and behold! </p>
<p class="ADBE_E_P ADBE_CM_CM3" id="ADBE_Obj_105" lang="en">
<span class="ADBE_E_Sub" data-page="1" id="ADBE_Obj_134">Reel away, reel away, </span><span class="ADBE_E_Sub" data-page="1" id="ADBE_Obj_135">Straw into gold!’ </span></p>
<p class="ADBE_E_P ADBE_CM_CM4 ADBE_CM_CM8" data-page="1" id="ADBE_Obj_106" lang="en">till, long before morning, all was done again. </p>
<p class="ADBE_E_P ADBE_CM_ADBE_CM_FULL_JUSTIFICATION ADBE_CM_CM1 ADBE_CM_CM8" id="ADBE_Obj_107" lang="en">
<span class="ADBE_E_ParagraphSpan ADBE_CM_ADBE_CM_FULL_JUSTIFICATION" data-page="1" id="ADBE_Obj_131">The king was greatly delighted to see all this glittering treasure; but still he had not enough: so he took the miller’s daughter to a yet larger heap, and said, ‘All this must be spun tonight; and if it is, you shall be my queen.’ As soon as she was alone that dwarf came in, and said, ‘What will you give me to spin gold for you this third time?’ ‘I have </span><span class="ADBE_E_ParagraphSpan ADBE_CM_ADBE_CM_FULL_JUSTIFICATION" data-page="2" id="ADBE_Obj_132">nothing left,’ said she. ‘Then say you will give me,’ said the little man, ‘the first little child that you may have when you are queen.’ ‘That may never be,’ thought the miller’s daughter: and as she knew no other way to get her task done, she said she would do what he asked. Round went the wheel again to the old song, and the manikin once more spun the heap into gold. The king came in the morning, and, finding all he wanted, was forced to keep his word; so he married the miller’s daughter, and she really became queen. </span></p>
<p class="ADBE_E_P ADBE_CM_ADBE_CM_FULL_JUSTIFICATION ADBE_CM_CM1 ADBE_CM_CM8" data-page="2" id="ADBE_Obj_108" lang="en">At the birth of her first little child she was very glad, and forgot the dwarf, and what she had said. But one day he came into her room, where she was sitting playing with her baby, and put her in mind of it. Then she grieved sorely at her misfortune, and said she would give him all the wealth of the kingdom if he would let her off, but in vain; till at last her tears softened him, and he said, ‘I will give you three days’ grace, and if during that time you tell me my name, you shall keep your child.’ </p>
<p class="ADBE_E_P ADBE_CM_ADBE_CM_FULL_JUSTIFICATION ADBE_CM_CM1 ADBE_CM_CM8" data-page="2" id="ADBE_Obj_109" lang="en">Now the queen lay awake all night, thinking of all the odd names that she had ever heard; and she sent messengers all over the land to find out new ones. The next day the little man came, and she began with TIMOTHY, ICHABOD, BENJAMIN, JEREMIAH, and all the names she could remember; but to all and each of them he said, ‘Madam, that is not my name.’ </p>
<p class="ADBE_E_P ADBE_CM_ADBE_CM_FULL_JUSTIFICATION ADBE_CM_CM1 ADBE_CM_CM8" data-page="2" id="ADBE_Obj_110" lang="en">The second day she began with all the comical names she could hear of, BANDY<span class="ADBE_E_HyphenSpan" data-page="2" id="ADBE_Obj_130">­</span>LEGS, HUNCHBACK, CROOK-SHANKS, and so on; but the little gentleman still said to every one of them, ‘Madam, that is not my name.’ </p>
<p class="ADBE_E_P ADBE_CM_ADBE_CM_FULL_JUSTIFICATION ADBE_CM_CM1 ADBE_CM_CM8" data-page="2" id="ADBE_Obj_111" lang="en">The third day one of the messengers came back, and said, ‘I have travelled two days without hearing of any other names; but yesterday, as I was climbing a high hill, among the trees of the forest where the fox and the hare bid each other good night, I saw a little hut; and before the hut burnt a fire; and round about the fire a funny little dwarf was dancing upon one leg, and singing: </p>
<p class="ADBE_E_P" id="ADBE_Obj_112" lang="en">
<span class="ADBE_E_Sub" data-page="2" id="ADBE_Obj_118">“Merrily the feast I’ll make. </span><span class="ADBE_E_Sub" data-page="2" id="ADBE_Obj_119">Today I’ll brew, tomorrow bake; </span><span class="ADBE_E_Sub" data-page="2" id="ADBE_Obj_120">Merrily I’ll dance and sing, </span><span class="ADBE_E_Sub" data-page="2" id="ADBE_Obj_121">For next day will a stranger bring. </span><span class="ADBE_E_Sub" data-page="2" id="ADBE_Obj_122">Little does my lady dream </span><span class="ADBE_E_Sub" data-page="2" id="ADBE_Obj_123">Rumpelstiltskin is my name!” </span></p>
<p class="ADBE_E_P ADBE_CM_ADBE_CM_FULL_JUSTIFICATION ADBE_CM_CM4 ADBE_CM_CM8" id="ADBE_Obj_113" lang="en">
<span class="ADBE_E_ParagraphSpan ADBE_CM_ADBE_CM_FULL_JUSTIFICATION" data-page="2" id="ADBE_Obj_114">When the queen heard this she jumped for joy, and as soon as her little friend came she sat down upon her throne, and called all her court round to enjoy the fun; and the nurse stood by her side with the baby in her arms, as if it was quite ready to be given up. Then the little man began to chuckle at the thought of having the poor child, to take home with him to his hut in the woods; and he cried out, ‘Now, lady, what is my name?’ ‘Is it JOHN?’ asked she. ‘No, madam!’ ‘Is it TOM?’ ‘No, madam!’ ‘Is it JEMMY?’ ‘It is not.’ ‘Can your name be RUMPELSTILTSKIN?’ said the lady slyly. ‘Some witch told you that!—some witch told you that!’ cried the little man, and dashed his right foot </span><span class="ADBE_E_ParagraphSpan" data-page="3" id="ADBE_Obj_90">in a rage so deep into the floor, that he was forced to lay hold of it with both hands to pull it out. </span></p>
<p class="ADBE_E_P ADBE_CM_ADBE_CM_FULL_JUSTIFICATION ADBE_CM_CM1" data-page="3" id="ADBE_Obj_91" lang="en">Then he made the best of his way off, while the nurse laughed and the baby crowed; and all the court jeered at him for having had so much trouble for nothing, and said, ‘We wish you a very good morning, and a merry feast, Mr RUMPLESTILTSKIN!’ </p>
</section>
</div>
</body>
</html>`,

Hansel_and_Gretel: `<html lang="EN-US" xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>Hansel_and_Gretel-tagged.pdf</title>
<meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
<meta content="width=device-width, initial-scale=1" name="viewport"/>
<meta content="pdfStructure" name="generator"/>
</head>
<body>
<div class="ADBE_E_Document" data-adbe-baseline-font-size="11" id="ADBE_Obj_133">
<h1 class="ADBE_E_Title" data-page="1" id="ADBE_Obj_129" lang="en">HANSEL AND GRETEL </h1>
<p class="ADBE_E_P ADBE_CM_ADBE_CM_FULL_JUSTIFICATION" data-page="1" id="ADBE_Obj_130" lang="en">Hard by a great forest dwelt a poor wood-cutter with his wife and his two children. The boy was called Hansel and the girl Gretel. He had little to bite and to break, and once when great dearth fell on the land, he could no longer procure even daily bread. Now when he thought over this by night in his bed, and tossed about in his anxiety, he groaned and said to his wife: ‘What is to become of us? How are we to feed our poor children, when we no longer have anything even for ourselves?’ ‘I’ll tell you what, husband,’ answered the woman, ‘early tomorrow morning we will take the children out into the forest to where it is the thickest; there we will light a fire for them, and give each of them one more piece of bread, and then we will go to our work and leave them alone. They will not find the way home again, and we shall be rid of them.’ ‘No, wife,’ said the man, ‘I will not do that; how can I bear to leave my children alone in the forest?—the wild animals would soon come and tear them to pieces.’ ‘O, you fool!’ said she, ‘then we must all four die of hunger, you may as well plane the planks for our coffins,’ and she left him no peace until he consented. ‘But I feel very sorry for the poor children, all the same,’ said the man. </p>
<p class="ADBE_E_P ADBE_CM_ADBE_CM_FULL_JUSTIFICATION" data-page="1" id="ADBE_Obj_131" lang="en">The two children had also not been able to sleep for hunger, and had heard what their stepmother had said to their father. Gretel wept bitter tears, and said to Hansel: ‘Now all is over with us.’ ‘Be quiet, Gretel,’ said Hansel, ‘do not distress yourself, I will soon find a way to help us.’ And when the old folks had fallen asleep, he got up, put on his little coat, opened the door below, and crept outside. The moon shone brightly, and the white pebbles which lay in front of the house glittered like real silver pennies. Hansel stooped and stuffed the little pocket of his coat with as many as he could get in. Then he went back and said to Gretel: ‘Be comforted, dear little sister, and sleep in peace, God will not forsake us,’ and he lay down again in his bed. When day dawned, but before the sun had risen, the woman came and awoke the two children, saying: ‘Get up, you sluggards! we are going into the forest to fetch wood.’ She gave each a little piece of bread, and said: ‘There is something for your dinner, but do not eat it up before then, for you will get nothing else.’ Gretel took the bread under her apron, as Hansel had the pebbles in his pocket. Then they all set out together on the way to the forest. When they had walked a short time, Hansel stood still and peeped back at the house, and did so again and again. His father said: ‘Hansel, what are you looking at there and staying behind for? Pay attention, and do not forget how to use your legs.’ ‘Ah, father,’ said Hansel, ‘I am looking at my little white cat, which is sitting up on the roof, and wants to say goodbye to me.’ The wife said: ‘Fool, that is not your little cat, that is the morning sun which is shining on the chimneys.’ Hansel, however, had not been looking back at the cat, but had been constantly throwing one of the white pebble-stones out of his pocket on the road. </p>
<p class="ADBE_E_P ADBE_CM_ADBE_CM_FULL_JUSTIFICATION" data-page="2" id="ADBE_Obj_159" lang="en">When they had reached the middle of the forest, the father said: ‘Now, children, pile up some wood, and I will light a fire that you may not be cold.’ Hansel and Gretel gathered brushwood together, as high as a little hill. The brushwood was lighted, and when the flames were burning very high, the woman said: ‘Now, children, lay yourselves down by the fire and rest, we will go into the forest and cut some wood. When we have done, we will come back and fetch you away.’ </p>
<p class="ADBE_E_P ADBE_CM_ADBE_CM_FULL_JUSTIFICATION" data-page="2" id="ADBE_Obj_160" lang="en">Hansel and Gretel sat by the fire, and when noon came, each ate a little piece of bread, and as they heard the strokes of the wood-axe they believed that their father was near. It was not the axe, however, but a branch which he had fastened to a withered tree which the wind was blowing backwards and forwards. And as they had been sitting such a long time, their eyes closed with fatigue, and they fell fast asleep. When at last they awoke, it was already dark night. Gretel began to cry and said: ‘How are we to get out of the forest now?’ But Hansel comforted her and said: ‘Just wait a little, until the moon has risen, and then we will soon find the way.’ And when the full moon had risen, Hansel took his little sister by the hand, and followed the pebbles which shone like newly-coined silver pieces, and showed them the way. </p>
<p class="ADBE_E_P ADBE_CM_ADBE_CM_FULL_JUSTIFICATION" data-page="2" id="ADBE_Obj_161" lang="en">They walked the whole night long, and by break of day came once more to their father’s house. They knocked at the door, and when the woman opened it and saw that it was Hansel and Gretel, she said: ‘You naughty children, why have you slept so long in the forest?—we thought you were never coming back at all!’ The father, however, rejoiced, for it had cut him to the heart to leave them behind alone. </p>
<p class="ADBE_E_P ADBE_CM_ADBE_CM_FULL_JUSTIFICATION" data-page="2" id="ADBE_Obj_162" lang="en">Not long afterwards, there was once more great dearth throughout the land, and the children heard their mother saying at night to their father: ‘Everything is eaten again, we have one half loaf left, and that is the end. The children must go, we will take them farther into the wood, so that they will not find their way out again; there is no other means of saving ourselves!’ The man’s heart was heavy, and he thought: ‘It would be better for you to share the last mouthful with your children.’ The woman, however, would listen to nothing that he had to say, but scolded and reproached him. He who says A must say B, likewise, and as he had yielded the first time, he had to do so a second time also. </p>
<p class="ADBE_E_P ADBE_CM_ADBE_CM_FULL_JUSTIFICATION" data-page="2" id="ADBE_Obj_163" lang="en">The children, however, were still awake and had heard the conversation. When the old folks were asleep, Hansel again got up, and wanted to go out and pick up pebbles as he had done before, but the woman had locked the door, and Hansel could not get out. Nevertheless he comforted his little sister, and said: ‘Do not cry, Gretel, go to sleep quietly, the good God will help us.’ </p>
<p class="ADBE_E_P ADBE_CM_ADBE_CM_FULL_JUSTIFICATION" id="ADBE_Obj_164" lang="en">
<span class="ADBE_E_ParagraphSpan ADBE_CM_ADBE_CM_FULL_JUSTIFICATION" data-page="2" id="ADBE_Obj_191">Early in the morning came the woman, and took the children out of their beds. Their piece of bread was given to them, but it was still smaller than the time before. On the way into the forest Hansel crumbled his in his pocket, and often stood still and threw a morsel on the ground. ‘Hansel, why do you stop and look round?’ said the father, ‘go on.’ ‘I am looking back at my little pigeon which is sitting on the roof, and wants to say </span><span class="ADBE_E_ParagraphSpan ADBE_CM_ADBE_CM_FULL_JUSTIFICATION" data-page="3" id="ADBE_Obj_192">goodbye to me,’ answered Hansel. ‘Fool!’ said the woman, ‘that is not your little pigeon, that is the morning sun that is shining on the chimney.’ Hansel, however little by little, threw all the crumbs on the path. </span></p>
<p class="ADBE_E_P ADBE_CM_ADBE_CM_FULL_JUSTIFICATION" data-page="3" id="ADBE_Obj_165" lang="en">The woman led the children still deeper into the forest, where they had never in their lives been before. Then a great fire was again made, and the mother said: ‘Just sit there, you children, and when you are tired you may sleep a little; we are going into the forest to cut wood, and in the evening when we are done, we will come and fetch you away.’ When it was noon, Gretel shared her piece of bread with Hansel, who had scattered his by the way. Then they fell asleep and evening passed, but no one came to the poor children. They did not awake until it was dark night, and Hansel comforted his little sister and said: ‘Just wait, Gretel, until the moon rises, and then we shall see the crumbs of bread which I have strewn about, they will show us our way home again.’ When the moon came they set out, but they found no crumbs, for the many thousands of birds which fly about in the woods and fields had picked them all up. Hansel said to Gretel: ‘We shall soon find the way,’ but they did not find it. They walked the whole night and all the next day too from morning till evening, but they did not get out of the forest, and were very hungry, for they had nothing to eat but two or three berries, which grew on the ground. And as they were so weary that their legs would carry them no longer, they lay down beneath a tree and fell asleep. </p>
<p class="ADBE_E_P ADBE_CM_ADBE_CM_FULL_JUSTIFICATION" data-page="3" id="ADBE_Obj_166" lang="en">It was now three mornings since they had left their father’s house. They began to walk again, but they always came deeper into the forest, and if help did not come soon, they must die of hunger and weariness. When it was mid-day, they saw a beautiful snow-white bird sitting on a bough, which sang so delightfully that they stood still and listened to it. And when its song was over, it spread its wings and flew away before them, and they followed it until they reached a little house, on the roof of which it alighted; and when they approached the little house they saw that it was built of bread and covered with cakes, but that the windows were of clear sugar. ‘We will set to work on that,’ said Hansel, ‘and have a good meal. I will eat a bit of the roof, and you Gretel, can eat some of the window, it will taste sweet.’ Hansel reached up above, and broke off a little of the roof to try how it tasted, and Gretel leant against the window and nibbled at the panes. Then a soft voice cried from the parlour: </p>
<p class="ADBE_E_P" data-page="3" id="ADBE_Obj_167" lang="en">‘Nibble, nibble, gnaw, </p>
<p class="ADBE_E_P" data-page="3" id="ADBE_Obj_168" lang="en">Who is nibbling at my little house?’ </p>
<p class="ADBE_E_P" data-page="3" id="ADBE_Obj_169" lang="en">The children answered: </p>
<p class="ADBE_E_P" data-page="3" id="ADBE_Obj_170" lang="en">‘The wind, the wind, </p>
<p class="ADBE_E_P" data-page="3" id="ADBE_Obj_171" lang="en">The heaven-born wind,’ </p>
<p class="ADBE_E_P ADBE_CM_ADBE_CM_FULL_JUSTIFICATION" id="ADBE_Obj_172" lang="en">
<span class="ADBE_E_ParagraphSpan ADBE_CM_ADBE_CM_FULL_JUSTIFICATION" data-page="3" id="ADBE_Obj_181">and went on eating without disturbing themselves. Hansel, who liked the taste of the roof, tore down a great piece of it, and Gretel pushed out the whole of one round window-pane, sat down, and enjoyed herself with it. Suddenly the door opened, and a woman as old as the hills, who supported herself on crutches, came creeping out. Hansel and Gretel were so terribly frightened that they let fall what they had in their hands. The </span><span class="ADBE_E_ParagraphSpan ADBE_CM_ADBE_CM_FULL_JUSTIFICATION" data-page="4" id="ADBE_Obj_182">old woman, however, nodded her head, and said: ‘Oh, you dear children, who has brought you here? do come in, and stay with me. No harm shall happen to you.’ She took them both by the hand, and led them into her little house. Then good food was set before them, milk and pancakes, with sugar, apples, and nuts. Afterwards two pretty little beds were covered with clean white linen, and Hansel and Gretel lay down in them, and thought they were in heaven. </span></p>
<p class="ADBE_E_P ADBE_CM_ADBE_CM_FULL_JUSTIFICATION" data-page="4" id="ADBE_Obj_173" lang="en">The old woman had only pretended to be so kind; she was in reality a wicked witch, who lay in wait for children, and had only built the little house of bread in order to entice them there. When a child fell into her power, she killed it, cooked and ate it, and that was a feast day with her. Witches have red eyes, and cannot see far, but they have a keen scent like the beasts, and are aware when human beings draw near. When Hansel and Gretel came into her neighbourhood, she laughed with malice, and said mockingly: ‘I have them, they shall not escape me again!’ Early in the morning before the children were awake, she was already up, and when she saw both of them sleeping and looking so pretty, with their plump and rosy cheeks she muttered to herself: ‘That will be a dainty mouthful!’ Then she seized Hansel with her shrivelled hand, carried him into a little stable, and locked him in behind a grated door. Scream as he might, it would not help him. Then she went to Gretel, shook her till she awoke, and cried: ‘Get up, lazy thing, fetch some water, and cook something good for your brother, he is in the stable outside, and is to be made fat. When he is fat, I will eat him.’ Gretel began to weep bitterly, but it was all in vain, for she was forced to do what the wicked witch commanded. </p>
<p class="ADBE_E_P ADBE_CM_ADBE_CM_FULL_JUSTIFICATION" data-page="4" id="ADBE_Obj_174" lang="en">And now the best food was cooked for poor Hansel, but Gretel got nothing but crab-shells. Every morning the woman crept to the little stable, and cried: ‘Hansel, stretch out your finger that I may feel if you will soon be fat.’ Hansel, however, stretched out a little bone to her, and the old woman, who had dim eyes, could not see it, and thought it was Hansel’s finger, and was astonished that there was no way of fattening him. When four weeks had gone by, and Hansel still remained thin, she was seized with impatience and would not wait any longer. ‘Now, then, Gretel,’ she cried to the girl, ‘stir yourself, and bring some water. Let Hansel be fat or lean, tomorrow I will kill him, and cook him.’ Ah, how the poor little sister did lament when she had to fetch the water, and how her tears did flow down her cheeks! ‘Dear God, do help us,’ she cried. ‘If the wild beasts in the forest had but devoured us, we should at any rate have died together.’ ‘Just keep your noise to yourself,’ said the old woman, ‘it won’t help you at all.’ </p>
<p class="ADBE_E_P ADBE_CM_ADBE_CM_FULL_JUSTIFICATION" id="ADBE_Obj_175" lang="en">
<span class="ADBE_E_ParagraphSpan ADBE_CM_ADBE_CM_FULL_JUSTIFICATION" data-page="4" id="ADBE_Obj_177">Early in the morning, Gretel had to go out and hang up the cauldron with the water, and light the fire. ‘We will bake first,’ said the old woman, ‘I have already heated the oven, and kneaded the dough.’ She pushed poor Gretel out to the oven, from which flames of fire were already darting. ‘Creep in,’ said the witch, ‘and see if it is properly heated, so that we can put the bread in.’ And once Gretel was inside, she intended to shut the oven and let her bake in it, and then she would eat her, too. But Gretel saw what she had in mind, and said: ‘I do not know how I am to do it; how do I get in?’ </span><span class="ADBE_E_ParagraphSpan ADBE_CM_ADBE_CM_FULL_JUSTIFICATION" data-page="5" id="ADBE_Obj_147">‘Silly goose,’ said the old woman. ‘The door is big enough; just look, I can get in myself!’ and she crept up and thrust her head into the oven. Then Gretel gave her a push that drove her far into it, and shut the iron door, and fastened the bolt. Oh! then she began to howl quite horribly, but Gretel ran away and the godless witch was miserably burnt to death. </span></p>
<p class="ADBE_E_P ADBE_CM_ADBE_CM_FULL_JUSTIFICATION" data-page="5" id="ADBE_Obj_148" lang="en">Gretel, however, ran like lightning to Hansel, opened his little stable, and cried: ‘Hansel, we are saved! The old witch is dead!’ Then Hansel sprang like a bird from its cage when the door is opened. How they did rejoice and embrace each other, and dance about and kiss each other! And as they had no longer any need to fear her, they went into the witch’s house, and in every corner there stood chests full of pearls and jewels. ‘These are far better than pebbles!’ said Hansel, and thrust into his pockets whatever could be got in, and Gretel said: ‘I, too, will take something home with me,’ and filled her pinafore full. ‘But now we must be off,’ said Hansel, ‘that we may get out of the witch’s forest.’ </p>
<p class="ADBE_E_P ADBE_CM_ADBE_CM_FULL_JUSTIFICATION" data-page="5" id="ADBE_Obj_149" lang="en">When they had walked for two hours, they came to a great stretch of water. ‘We cannot cross,’ said Hansel, ‘I see no foot-plank, and no bridge.’ ‘And there is also no ferry,’ answered Gretel, ‘but a white duck is swimming there: if I ask her, she will help us over.’ Then she cried: </p>
<div class="ADBE_E_Footnote" data-page="5" id="ADBE_Obj_150" lang="en">‘Little duck, little duck, dost thou see, Hansel and Gretel are waiting for thee? There’s never a plank, or bridge in sight, Take us across on thy back so white.’ </div>
<p class="ADBE_E_P ADBE_CM_ADBE_CM_FULL_JUSTIFICATION" data-page="5" id="ADBE_Obj_151" lang="en">The duck came to them, and Hansel seated himself on its back, and told his sister to sit by him. ‘No,’ replied Gretel, ‘that will be too heavy for the little duck; she shall take us across, one after the other.’ The good little duck did so, and when they were once safely across and had walked for a short time, the forest seemed to be more and more familiar to them, and at length they saw from afar their father’s house. Then they began to run, rushed into the parlour, and threw themselves round their father’s neck. The man had not known one happy hour since he had left the children in the forest; the woman, however, was dead. Gretel emptied her pinafore until pearls and precious stones ran about the room, and Hansel threw one handful after another out of his pocket to add to them. Then all anxiety was at an end, and they lived together in perfect happiness. My tale is done, there runs a mouse; whosoever catches it, may make himself a big fur cap out of it. </p>
</div>
</body>
</html>
`}

const SimpleFileChooser = (props: {
  updateControlValue: (name: string, source: string, value: ControlValue) => void
}) => {
  return (<Picker label="File name" labelPosition="side" placeholder="Select file..."
                  onSelectionChange={(key) => {
                    props.updateControlValue('html', 'picker', fileHTML[key]);
                    addLogRecord('fileName', 'picker', '', key);
                  }}
                  >
    <Item key="Learning_from_History">Learning from History</Item>
    <Item key="Rapunzel">Rapunzel</Item>
    <Item key="Rumpelstiltskin">Rumpelstiltskin</Item>
    <Item key="Hansel_and_Gretel">Hansel and Gretel</Item>
  </Picker>)
}

export default SimpleFileChooser